#!/bin/bash

if [ -z $1 ]; then
	echo "usage: ./hive_api function_name parameters"
	echo "function: all_workers_stat | worker_stat | fs_list | oc_list | fs_apply FS_ID | oc_apply OC_ID"
	exit
fi


baseUrl='https://api2.hiveos.farm/api/v2'
login="you_login"
password="you_passwd"
TOKEN="/hive-config/token"
accessToken=""
FARM_ID=you_FARM_ID #Not worker ID!!!
RIG_ID=you_RIG_ID #Worker ID


function login {
	response=`curl -s -w "\n%{http_code}" \
		-H "Content-Type: application/json" \
		-X POST \
		-d "{\"login\":\"$login\",\"password\":\"$password\",\"remember\": true}" \
		"$baseUrl/auth/login"`
	[ $? -ne 0 ] && (>&2 echo 'Curl error') && exit 1
	statusCode=`echo "$response" | tail -1`
	response=`echo "$response" | sed '$d'`
	[[ $statusCode -lt 200 || $statusCode -ge 300 ]] && { echo "$response" | jq 1>&2; } && exit 1

	# Extract access token
	accessToken=`echo "$response" | jq --raw-output '.access_token'`
	echo "accessToken=\"$accessToken\"" > $TOKEN
}

function check_token {
	response=`curl -s -w "\n%{http_code}" \
		-H "Content-Type: application/json" \
		-H "Authorization: Bearer $accessToken" \
		"$baseUrl/auth/check"`
	[ $? -ne 0 ] && (>&2 echo 'Curl error') && exit 1
	statusCode=`echo "$response" | tail -1`
	[[ $statusCode -lt 200 || $statusCode -ge 300 ]] && { echo "$response" | jq 1>&2; } && exit 1
	if [ $statusCode -eq 204 ]; then
		echo true
	else
		echo false
	fi
}


function all_workers_stat {
response=`curl -s -w "\n%{http_code}" \
	 -H "Content-Type: application/json" \
	 -H "Authorization: Bearer $accessToken" \
	 "$baseUrl/farms/$FARM_ID/workers"`
	 
[ $? -ne 0 ] && (>&2 echo 'Curl error') && exit 1
statusCode=`echo "$response" | tail -1`
response=`echo "$response" | sed '$d'`
[[ $statusCode -lt 200 || $statusCode -ge 300 ]] && { echo "$response" | jq 1>&2; } && exit 1

# Display farms
echo "$response"
}


function worker_stat {
response=`curl -s -w "\n%{http_code}" \
	 -H "Content-Type: application/json" \
	 -H "Authorization: Bearer $accessToken" \
	 "$baseUrl/farms/$FARM_ID/workers/$RIG_ID"`
	 
[ $? -ne 0 ] && (>&2 echo 'Curl error') && exit 1
statusCode=`echo "$response" | tail -1`
response=`echo "$response" | sed '$d'`
[[ $statusCode -lt 200 || $statusCode -ge 300 ]] && { echo "$response" | jq 1>&2; } && exit 1

# Display farms
echo "$response"
}


function fs_list {
response=`curl -s -w "\n%{http_code}" \
	 -H "Content-Type: application/json" \
	 -H "Authorization: Bearer $accessToken" \
	 "$baseUrl/farms/$FARM_ID/fs"`
	 


# Display farms
echo "$response"
}

function oc_list {
response=`curl -s -w "\n%{http_code}" \
	 -H "Content-Type: application/json" \
	 -H "Authorization: Bearer $accessToken" \
	 "$baseUrl/farms/$FARM_ID/oc"`
	 


# Display farms
echo "$response"
}


function fs_apply {
response=`curl -s -w "\n%{http_code}" \
	 -H "Content-Type: application/json" \
	 -H "Authorization: Bearer $accessToken" \
	 -X PATCH \
	 -d "{\"fs_id\": $1}" \
	 "$baseUrl/farms/$FARM_ID/workers/$RIG_ID"`
	 
[ $? -ne 0 ] && (>&2 echo 'Curl error') && exit 1
statusCode=`echo "$response" | tail -1`
response=`echo "$response" | sed '$d'`
[[ $statusCode -lt 200 || $statusCode -ge 300 ]] && { echo "$response" | jq 1>&2; } && exit 1

# Display farms
echo "$response"
}


function oc_apply {
response=`curl -s -w "\n%{http_code}" \
	 -H "Content-Type: application/json" \
	 -H "Authorization: Bearer $accessToken" \
	 -X PATCH \
	 -d "{\"oc_id\": $1}" \
	 "$baseUrl/farms/$FARM_ID/workers/$RIG_ID"`
	 
[ $? -ne 0 ] && (>&2 echo 'Curl error') && exit 1
statusCode=`echo "$response" | tail -1`
response=`echo "$response" | sed '$d'`
[[ $statusCode -lt 200 || $statusCode -ge 300 ]] && { echo "$response" | jq 1>&2; } && exit 1

# Display farms
echo "$response"
}


[ -f $TOKEN ] && source $TOKEN
[ -z $accessToken ] && login

[ ! $(check_token) ] && login

echo $($1 $2) | jq .
exit 0
